/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductDocRouteImport } from './routes/product-doc'
import { Route as ApiDocRouteImport } from './routes/api-doc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbedMovieTmdbIdRouteImport } from './routes/embed/movie/$tmdbId'
import { Route as DownloadMovieTmdbIdRouteImport } from './routes/download/movie/$tmdbId'
import { Route as StreamAnimeAnilistIdEpisodeRouteImport } from './routes/stream/anime/$anilistId/$episode'
import { Route as DownloadAnimeAnilistIdEpisodeRouteImport } from './routes/download/anime/$anilistId/$episode'
import { Route as EmbedTvTmdbIdSeasonEpisodeRouteImport } from './routes/embed/tv/$tmdbId/$season/$episode'
import { Route as DownloadTvTmdbIdSeasonEpisodeRouteImport } from './routes/download/tv/$tmdbId/$season/$episode'

const ProductDocRoute = ProductDocRouteImport.update({
  id: '/product-doc',
  path: '/product-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocRoute = ApiDocRouteImport.update({
  id: '/api-doc',
  path: '/api-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedMovieTmdbIdRoute = EmbedMovieTmdbIdRouteImport.update({
  id: '/embed/movie/$tmdbId',
  path: '/embed/movie/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadMovieTmdbIdRoute = DownloadMovieTmdbIdRouteImport.update({
  id: '/download/movie/$tmdbId',
  path: '/download/movie/$tmdbId',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamAnimeAnilistIdEpisodeRoute =
  StreamAnimeAnilistIdEpisodeRouteImport.update({
    id: '/stream/anime/$anilistId/$episode',
    path: '/stream/anime/$anilistId/$episode',
    getParentRoute: () => rootRouteImport,
  } as any)
const DownloadAnimeAnilistIdEpisodeRoute =
  DownloadAnimeAnilistIdEpisodeRouteImport.update({
    id: '/download/anime/$anilistId/$episode',
    path: '/download/anime/$anilistId/$episode',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmbedTvTmdbIdSeasonEpisodeRoute =
  EmbedTvTmdbIdSeasonEpisodeRouteImport.update({
    id: '/embed/tv/$tmdbId/$season/$episode',
    path: '/embed/tv/$tmdbId/$season/$episode',
    getParentRoute: () => rootRouteImport,
  } as any)
const DownloadTvTmdbIdSeasonEpisodeRoute =
  DownloadTvTmdbIdSeasonEpisodeRouteImport.update({
    id: '/download/tv/$tmdbId/$season/$episode',
    path: '/download/tv/$tmdbId/$season/$episode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-doc': typeof ApiDocRoute
  '/product-doc': typeof ProductDocRoute
  '/download/movie/$tmdbId': typeof DownloadMovieTmdbIdRoute
  '/embed/movie/$tmdbId': typeof EmbedMovieTmdbIdRoute
  '/download/anime/$anilistId/$episode': typeof DownloadAnimeAnilistIdEpisodeRoute
  '/stream/anime/$anilistId/$episode': typeof StreamAnimeAnilistIdEpisodeRoute
  '/download/tv/$tmdbId/$season/$episode': typeof DownloadTvTmdbIdSeasonEpisodeRoute
  '/embed/tv/$tmdbId/$season/$episode': typeof EmbedTvTmdbIdSeasonEpisodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-doc': typeof ApiDocRoute
  '/product-doc': typeof ProductDocRoute
  '/download/movie/$tmdbId': typeof DownloadMovieTmdbIdRoute
  '/embed/movie/$tmdbId': typeof EmbedMovieTmdbIdRoute
  '/download/anime/$anilistId/$episode': typeof DownloadAnimeAnilistIdEpisodeRoute
  '/stream/anime/$anilistId/$episode': typeof StreamAnimeAnilistIdEpisodeRoute
  '/download/tv/$tmdbId/$season/$episode': typeof DownloadTvTmdbIdSeasonEpisodeRoute
  '/embed/tv/$tmdbId/$season/$episode': typeof EmbedTvTmdbIdSeasonEpisodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-doc': typeof ApiDocRoute
  '/product-doc': typeof ProductDocRoute
  '/download/movie/$tmdbId': typeof DownloadMovieTmdbIdRoute
  '/embed/movie/$tmdbId': typeof EmbedMovieTmdbIdRoute
  '/download/anime/$anilistId/$episode': typeof DownloadAnimeAnilistIdEpisodeRoute
  '/stream/anime/$anilistId/$episode': typeof StreamAnimeAnilistIdEpisodeRoute
  '/download/tv/$tmdbId/$season/$episode': typeof DownloadTvTmdbIdSeasonEpisodeRoute
  '/embed/tv/$tmdbId/$season/$episode': typeof EmbedTvTmdbIdSeasonEpisodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-doc'
    | '/product-doc'
    | '/download/movie/$tmdbId'
    | '/embed/movie/$tmdbId'
    | '/download/anime/$anilistId/$episode'
    | '/stream/anime/$anilistId/$episode'
    | '/download/tv/$tmdbId/$season/$episode'
    | '/embed/tv/$tmdbId/$season/$episode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-doc'
    | '/product-doc'
    | '/download/movie/$tmdbId'
    | '/embed/movie/$tmdbId'
    | '/download/anime/$anilistId/$episode'
    | '/stream/anime/$anilistId/$episode'
    | '/download/tv/$tmdbId/$season/$episode'
    | '/embed/tv/$tmdbId/$season/$episode'
  id:
    | '__root__'
    | '/'
    | '/api-doc'
    | '/product-doc'
    | '/download/movie/$tmdbId'
    | '/embed/movie/$tmdbId'
    | '/download/anime/$anilistId/$episode'
    | '/stream/anime/$anilistId/$episode'
    | '/download/tv/$tmdbId/$season/$episode'
    | '/embed/tv/$tmdbId/$season/$episode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocRoute: typeof ApiDocRoute
  ProductDocRoute: typeof ProductDocRoute
  DownloadMovieTmdbIdRoute: typeof DownloadMovieTmdbIdRoute
  EmbedMovieTmdbIdRoute: typeof EmbedMovieTmdbIdRoute
  DownloadAnimeAnilistIdEpisodeRoute: typeof DownloadAnimeAnilistIdEpisodeRoute
  StreamAnimeAnilistIdEpisodeRoute: typeof StreamAnimeAnilistIdEpisodeRoute
  DownloadTvTmdbIdSeasonEpisodeRoute: typeof DownloadTvTmdbIdSeasonEpisodeRoute
  EmbedTvTmdbIdSeasonEpisodeRoute: typeof EmbedTvTmdbIdSeasonEpisodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/product-doc': {
      id: '/product-doc'
      path: '/product-doc'
      fullPath: '/product-doc'
      preLoaderRoute: typeof ProductDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-doc': {
      id: '/api-doc'
      path: '/api-doc'
      fullPath: '/api-doc'
      preLoaderRoute: typeof ApiDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/movie/$tmdbId': {
      id: '/embed/movie/$tmdbId'
      path: '/embed/movie/$tmdbId'
      fullPath: '/embed/movie/$tmdbId'
      preLoaderRoute: typeof EmbedMovieTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/movie/$tmdbId': {
      id: '/download/movie/$tmdbId'
      path: '/download/movie/$tmdbId'
      fullPath: '/download/movie/$tmdbId'
      preLoaderRoute: typeof DownloadMovieTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stream/anime/$anilistId/$episode': {
      id: '/stream/anime/$anilistId/$episode'
      path: '/stream/anime/$anilistId/$episode'
      fullPath: '/stream/anime/$anilistId/$episode'
      preLoaderRoute: typeof StreamAnimeAnilistIdEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/anime/$anilistId/$episode': {
      id: '/download/anime/$anilistId/$episode'
      path: '/download/anime/$anilistId/$episode'
      fullPath: '/download/anime/$anilistId/$episode'
      preLoaderRoute: typeof DownloadAnimeAnilistIdEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/tv/$tmdbId/$season/$episode': {
      id: '/embed/tv/$tmdbId/$season/$episode'
      path: '/embed/tv/$tmdbId/$season/$episode'
      fullPath: '/embed/tv/$tmdbId/$season/$episode'
      preLoaderRoute: typeof EmbedTvTmdbIdSeasonEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/tv/$tmdbId/$season/$episode': {
      id: '/download/tv/$tmdbId/$season/$episode'
      path: '/download/tv/$tmdbId/$season/$episode'
      fullPath: '/download/tv/$tmdbId/$season/$episode'
      preLoaderRoute: typeof DownloadTvTmdbIdSeasonEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocRoute: ApiDocRoute,
  ProductDocRoute: ProductDocRoute,
  DownloadMovieTmdbIdRoute: DownloadMovieTmdbIdRoute,
  EmbedMovieTmdbIdRoute: EmbedMovieTmdbIdRoute,
  DownloadAnimeAnilistIdEpisodeRoute: DownloadAnimeAnilistIdEpisodeRoute,
  StreamAnimeAnilistIdEpisodeRoute: StreamAnimeAnilistIdEpisodeRoute,
  DownloadTvTmdbIdSeasonEpisodeRoute: DownloadTvTmdbIdSeasonEpisodeRoute,
  EmbedTvTmdbIdSeasonEpisodeRoute: EmbedTvTmdbIdSeasonEpisodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
